[pytest]
DJANGO_SETTINGS_MODULE = core.settings_test
pythonpath = .
python_files = test_*.py
addopts = --tb=short

[coverage:run]
branch = true
source = apps,core
omit = */migrations/*,*/tests/*

[mypy]
python_version = 3.13
pretty = true
show_error_codes = true
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
plugins = mypy_django_plugin.main, mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = core.settings_test
