# Generated by Django 5.2.17 on 2026-09-02 10:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instructor_id', models.CharField(db_index=True, max_length=50)),
                ('instructor_fio', models.CharField(max_length=255)),
                ('discipline_name', models.CharField(max_length=255)),
                ('education_direction', models.CharField(max_length=255)),
                ('course_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('generating', 'Генерация'), ('ready', 'Готов'), ('error', 'Ошибка')], db_index=True, default='draft', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('objectives', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('presentation', 'Презентация'), ('theory', 'Теория'), ('quiz', 'Самопроверка'), ('test', 'Тест')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('source_meta', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='courses.coursesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlockRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField(default=dict)),
                ('source_meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='courses.contentblock')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('block', 'version')},
            },
        ),
    ]
