# Generated by Django 5.2.17 on 2026-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaterial',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
